/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import java.io.BufferedReader;
import java.io.IOException;
import java.lang.reflect.Type;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;

public class App {
    public String getGreeting() {

        return "Hello World!";
    }

    public static BufferedReader fileReader;

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Path path = Paths.get("app/src/main/resources/recentquotes.json");

        ArrayList<Quotes> quotes = readerFunction(path);
        int random = (int) (Math.random() * (quotes.size()));
        System.out.println(quotes.get(random).toString());


    }

    public static ArrayList<Quotes> readerFunction(Path path) {

        Gson gson = new Gson();

        try {
            fileReader = Files.newBufferedReader(path);
        } catch (IOException exception) {
            exception.printStackTrace();
        }

        Type qouteList = new TypeToken<ArrayList<Quotes>>() {
        }.getType();
        ArrayList<Quotes> quotes = gson.fromJson(fileReader, qouteList);
        return quotes;
    }

}



